[build]
  publish = "public"
  command = ""
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package.json"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 